### ISSUE TITLE
Remove theRsidR Property

### ISSUE THREAD

**Issue by ahadshafiq** [OfficeDev/Open-XML-Package-Editor-Power-Tool-for-Visual-Studio#3]
I hope the issue tracker is an OK place to ask questions. 

I'd like to ask where in the repository lies the code that adds the RsidR attributes to the <w:p> tags for .docx word documents. I'd like to fork the code to be able to eliminate these (along with other tags).

**Comment by pugwonk** [comment]
Hi there - the package editor doesn't actually do anything clever inside the XML files (beyond tracking relationships). I'm not sure the package editor is the best way to try and do this - you might have more luck with the Open XML SDK (https://github.com/OfficeDev/Open-XML-SDK).
