### ISSUE TITLE
VS2015 Support

### ISSUE THREAD

**Issue by wmaurer** [OfficeDev/Open-XML-Package-Editor-Power-Tool-for-Visual-Studio#6]
The Open XML Package Editor for Visual Studio extension is not currently compatible with VS2015. What are the plans for adding VS2015 support?

**Comment by duncansmart** [comment]
@wmaurer Until this gets merged and published you can [download the VSIX file](https://visualstudiogallery.msdn.microsoft.com/450a00e3-5a7d-4776-be2c-8aa8cec2a75b/file/30841/1/OpenXMLEditor.vsix) open it as a ZIP file and edit the extension.vsixmanifest file as to add the `<VisualStudio Version="14.0">` section, then it should insyall into VS2015
